#!/bin/sh
###########################################################################
#   This shell script takes care of starting and stopping
#   cpci5125 driver.
###########################################################################

# Source function library.
. /etc/rc.d/init.d/functions

# See how we were called.
case "$1" in
  start)
        # load driver module.
        echo  "Starting cpci5125 driver: "

        if sh /etc/rc.d/init.d/cpci5125_load 
        then
            action "cpci5125 driver: " /bin/true
        else
            action "cpci5125 driver: " /bin/false
        fi
        ;;
  stop)
        # uload driver module.
        echo "Stopping cpci5125 driver: "

	if sh /etc/rc.d/init.d/cpci5125_unload
	then
	    action "cpci5125 driver: " /bin/true
	else
	    action "cpci5125 driver: " /bin/false
	fi
        ;;
  restart|reload)
	sh $0 stop
	sh $0 start
	;;
  *)
        echo "Usage: cpci5125_init {start|stop|restart|reload}"
        exit 1
esac

exit 0
