#!/bin/sh
###########################################################################
#   Installation shell script for the cpci5125 device driver (Linux)
###########################################################################

PATCHLEVEL=`uname -r | cut -d. -f2`

if [ ${PATCHLEVEL} = 4 ]; then
MODULE=cPCI5125.o
MOD_DIR=/lib/modules/`uname -r`/cPCI5125
else
MODULE=cPCI5125.ko
MOD_DIR=/lib/modules/`uname -r`/extra
fi

DEVICE=cPCI5125
MODE="666"

echo  "Loading Module cPCI5125."
# Install the module
/sbin/insmod -f ${MOD_DIR}/${MODULE} $* #|| exit 1
echo "Module "${DEVICE}" has been installed."
# Remove stale character device nodes
rm -f /dev/${DEVICE}[0-4]
echo "Stale device nodes /dev/"${DEVICE}"[0-4] have been removed."

# Determine the major device number
major=`cat /proc/devices | awk "\\$2==\"$DEVICE\" {print \\$1}"`
echo "New major device number is "${major}"."

dev="6432:5125"
# Determine how many cpci5125 devices are present
#count=`cat /proc/rfm2g | grep RFM2G_DEVICE_COUNT | awk '{print $2}'`
count=`lspci -n | grep 6432:5125 | wc -l`
echo $count
# Create new character device nodes
minor=0
while [ $minor -lt $count ] 
do
    mknod /dev/${DEVICE}${minor} c ${major} ${minor}
    echo "New device node /dev/"${DEVICE}${minor}" has been created."
    minor=`expr $minor + 1`
done

# Set permissions
chmod ${MODE} /dev/${DEVICE}[0-4]

echo

exit 0

